#!/bin/sh
cd ${0%/*} || exit 1    # run from this directory

if [ "$1" = "wmake" ] || [ "$1" = "wclean" ]; then
    wcmd="$1"
    shift
else
    wcmd="wmake"
fi

# ============================================================================
# Build/Clean ThirdParty dependencies (MoorDyn v1 and v2)
# ============================================================================
echo "========================================"
if [ "$wcmd" = "wmake" ]; then
    echo "  Building ThirdParty (MoorDyn)"
else
    echo "  Cleaning ThirdParty (MoorDyn)"
fi
echo "========================================"
cd ThirdParty/MoorDyn
if [ "$wcmd" = "wmake" ]; then
    ./Allwmake
else
    ./Allwclean
fi
if [ $? -ne 0 ]; then
    if [ "$wcmd" = "wmake" ]; then
        echo "ERROR: ThirdParty build failed"
        exit 1
    else
        echo "WARNING: ThirdParty clean had issues, continuing"
    fi
fi
cd ../..

echo ""
echo "========================================"
echo "  ${wcmd}ing floatStepperWaveFoam"
echo "========================================"


$wcmd "$@" src/functionObjects/forceContributions
$wcmd "$@" src/addedMass
$wcmd "$@" src/floaterMotion
$wcmd "$@" src/functionObjects/floaterStateWriter
$wcmd "$@" src/functionObjects/sixDoFRigidBodyStateWriter
$wcmd "$@" src/functionObjects/addedMassWriter
$wcmd "$@" src/waveMakerMotionSolver
$wcmd "$@" applications/floatStepper
$wcmd "$@" applications/util/joukowskiTransformPoints
$wcmd "$@" applications/util/floaterInertia
$wcmd "$@" applications/util/KirchhoffKelvinIntegrator2D
$wcmd "$@" applications/util/addedMassCalculator
$wcmd "$@" applications/util/kelvinKirchhoffEquationSolver
$wcmd "$@" applications/util/floaterMotionPotentialFlow